[book]
authors = ["Lukáš Hozda"]
language = "cs"
multilingual = false
src = "src"
title = "GJK Cat Informatika - Repozitář studijních materiálů z informatiky"
create-missing = true

[preprocessor.links]
[output.html]
theme = "src/theme"

[output.html.fold]
enabled = true
level = 0

[output.html.playpen]
editable = true
copyable = true
copy-js = true

[preprocessor.cat-prep]
