#!/bin/sh

curl https://sh.rustup.rs -sSf | sh -s -- --profile minimal --default-toolchain nightly -y

source $HOME/.cargo/env

cargo install mdbook
cargo install mdbook-cat-prep

# reclone required because we need git
git clone https://github.com/gjk-cat/tr.gjk.cat

cd tr.gjk.cat

mdbook build

cp -r book ../book
